GENRES = [u'a cappella'
, u'abstract'
, u'abstract hip hop'
, u'abstract idm'
, u'accordion'
, u'acid house'
, u'acid jazz'
, u'acid techno'
, u'acousmatic'
, u'acoustic blues'
, u'acoustic pop'
, u'adult standards'
, u'african percussion'
, u'african rock'
, u'afrikaans'
, u'afrobeat'
, u'afrobeats'
, u'aggrotech'
, u'albanian pop'
, u'album rock'
, u'albuquerque indie'
, u'alternative americana'
, u'alternative country'
, u'alternative dance'
, u'alternative emo'
, u'alternative hardcore'
, u'alternative hip hop'
, u'alternative metal'
, u'alternative metalcore'
, u'alternative new age'
, u'alternative pop'
, u'alternative pop rock'
, u'alternative r&b'
, u'alternative rock'
, u'alternative roots rock'
, u'ambeat'
, u'ambient'
, u'ambient dub techno'
, u'ambient fusion'
, u'ambient idm'
, u'ambient psychill'
, u'ambient trance'
, u'anarcho-punk'
, u'andean'
, u'anime'
, u'anime score'
, u'anti-folk'
, u'antiviral pop'
, u'appalachian folk'
, u'arab folk'
, u'arab pop'
, u'arabesk'
, u'argentine indie'
, u'argentine reggae'
, u'argentine rock'
, u'armenian folk'
, u'art rock'
, u'athens indie'
, u'atmospheric black metal'
, u'atmospheric post rock'
, u'atmospheric post-metal'
, u'aussietronica'
, u'austindie'
, u'australian alternative rock'
, u'australian country'
, u'australian dance'
, u'australian hip hop'
, u'australian indie'
, u'australian pop'
, u'austrian hip hop'
, u'austropop'
, u'avant-garde'
, u'avant-garde jazz'
, u'avantgarde metal'
, u'axe'
, u'azonto'
, u'bachata'
, u'baile funk'
, u'balearic'
, u'balkan brass'
, u'banda'
, u'bangla'
, u'barbershop'
, u'barnemusikk'
, u'baroque'
, u'baroque ensemble'
, u'basque rock'
, u'bass music'
, u'bass trip'
, u'bassline'
, u'bay area hip hop'
, u'beach music'
, u'beatdown'
, u'beats & rhymes'
, u'bebop'
, u'belgian indie'
, u'belgian rock'
, u'belly dance'
, u'belorush'
, u'bemani'
, u'benga'
, u'bhangra'
, u'big band'
, u'big beat'
, u'big room'
, u'black death'
, u'black metal'
, u'black sludge'
, u'black thrash'
, u'blackgaze'
, u'blaskapelle'
, u'bluegrass'
, u'blues'
, u'blues-rock'
, u'blues-rock guitar'
, u'bmore'
, u'bolero'
, u'boogaloo'
, u'boogie-woogie'
, u'bossa nova'
, u'bossa nova jazz'
, u'boston rock'
, u'bounce'
, u'bouncy house'
, u'bow pop'
, u'boy band'
, u'brass band'
, u'brass ensemble'
, u'brazilian composition'
, u'brazilian gospel'
, u'brazilian hip hop'
, u'brazilian indie'
, u'brazilian pop music'
, u'brazilian punk'
, u'breakbeat'
, u'breakcore'
, u'breaks'
, u'brega'
, u'breton folk'
, u'brill building pop'
, u'british alternative rock'
, u'british blues'
, u'british brass band'
, u'british dance band'
, u'british folk'
, u'british indie rock'
, u'british invasion'
, u'britpop'
, u'broadway'
, u'broken beat'
, u'brooklyn indie'
, u'brostep'
, u'brutal death metal'
, u'brutal deathcore'
, u'bubble trance'
, u'bubblegum dance'
, u'bubblegum pop'
, u'bulgarian rock'
, u'byzantine'
, u'c-pop'
, u'c64'
, u'c86'
, u'cabaret'
, u'cajun'
, u'calypso'
, u'canadian country'
, u'canadian hip hop'
, u'canadian indie'
, u'canadian metal'
, u'canadian pop'
, u'candy pop'
, u'cantautor'
, u'cante flamenco'
, u'canterbury scene'
, u'cantopop'
, u'canzone napoletana'
, u'capoeira'
, u'carnatic'
, u'catstep'
, u'caucasian folk'
, u'ccm'
, u'ceilidh'
, u'cello'
, u'celtic'
, u'celtic christmas'
, u'celtic punk'
, u'celtic rock'
, u'central asian folk'
, u'chalga'
, u'chamber pop'
, u'chanson'
, u'chanson quebecois'
, u'chaotic black metal'
, u'chaotic hardcore'
, u'charred death'
, u'chicago blues'
, u'chicago house'
, u'chicago indie'
, u'chicago soul'
, u'chicano rap'
, u"children's christmas"
, u"children's music"
, u'chilean rock'
, u'chill groove'
, u'chill lounge'
, u'chill-out'
, u'chill-out trance'
, u'chillstep'
, u'chillwave'
, u'chinese indie rock'
, u'chinese opera'
, u'chinese traditional'
, u'chip hop'
, u'chiptune'
, u'choral'
, u'choro'
, u'christian alternative rock'
, u'christian christmas'
, u'christian dance'
, u'christian hardcore'
, u'christian hip hop'
, u'christian metal'
, u'christian music'
, u'christian punk'
, u'christian rock'
, u'christmas'
, u'christmas product'
, u'cinematic dubstep'
, u'clarinet'
, u'classic afrobeat'
, u'classic belgian pop'
, u'classic chinese pop'
, u'classic colombian pop'
, u'classic czech pop'
, u'classic danish pop'
, u'classic dutch pop'
, u'classic eurovision'
, u'classic finnish pop'
, u'classic finnish rock'
, u'classic french pop'
, u'classic funk rock'
, u'classic garage rock'
, u'classic italian pop'
, u'classic norwegian pop'
, u'classic peruvian pop'
, u'classic polish pop'
, u'classic psychedelic rock'
, u'classic rock'
, u'classic russian pop'
, u'classic russian rock'
, u'classic schlager'
, u'classic soundtrack'
, u'classic swedish pop'
, u'classic turkish pop'
, u'classic venezuelan pop'
, u'classical'
, u'classical christmas'
, u'classical flute'
, u'classical guitar'
, u'classical organ'
, u'classical performance'
, u'classical period'
, u'classical piano'
, u'college a cappella'
, u'college marching band'
, u'colombian rock'
, u'columbus ohio indie'
, u'comedy'
, u'comedy rock'
, u'comic'
, u'commons'
, u'complextro'
, u'composition d'
, u'concert piano'
, u'consort'
, u'contemporary classical'
, u'contemporary country'
, u'contemporary folk'
, u'contemporary jazz'
, u'contemporary post-bop'
, u'cool jazz'
, u'corrosion'
, u'corsican folk'
, u'country'
, u'country blues'
, u'country christmas'
, u'country dawn'
, u'country gospel'
, u'country road'
, u'country rock'
, u'coupe decale'
, u'coverchill'
, u'covertrance'
, u'cowboy western'
, u'cowpunk'
, u'crack rock steady'
, u'croatian pop'
, u'crossover prog'
, u'crossover thrash'
, u'crunk'
, u'crust punk'
, u'cryptic black metal'
, u'cuban rumba'
, u'cubaton'
, u'cumbia'
, u'cumbia funk'
, u'cumbia sonidera'
, u'cumbia villera'
, u'cyber metal'
, u'czech folk'
, u'czech rock'
, u'dallas indie'
, u'dance pop'
, u'dance rock'
, u'dance-punk'
, u'dancehall'
, u'dangdut'
, u'danish hip hop'
, u'danish indie'
, u'danish jazz'
, u'danish pop'
, u'danish pop rock'
, u'dansband'
, u'danseband'
, u'dark ambient'
, u'dark black metal'
, u'dark cabaret'
, u'dark electro-industrial'
, u'dark hardcore'
, u'dark jazz'
, u'dark minimal techno'
, u'dark progressive house'
, u'dark psytrance'
, u'dark wave'
, u'darkstep'
, u'death core'
, u'death metal'
, u'deathgrind'
, u'deep acoustic pop'
, u'deep adult standards'
, u'deep alternative r&b'
, u'deep ambient'
, u'deep baroque'
, u'deep brazilian pop'
, u'deep breakcore'
, u'deep canadian indie'
, u'deep ccm'
, u'deep cello'
, u'deep chill'
, u'deep chill-out'
, u'deep christian rock'
, u'deep classic garage rock'
, u'deep classical piano'
, u'deep comedy'
, u'deep contemporary country'
, u'deep dance pop'
, u'deep darkpsy'
, u'deep deep house'
, u'deep deep tech house'
, u'deep delta blues'
, u'deep disco'
, u'deep disco house'
, u'deep discofox'
, u'deep downtempo fusion'
, u'deep dub techno'
, u'deep east coast hip hop'
, u'deep euro house'
, u'deep eurodance'
, u'deep filthstep'
, u'deep flow'
, u'deep folk metal'
, u'deep free jazz'
, u'deep freestyle'
, u'deep full on'
, u'deep funk'
, u'deep funk house'
, u'deep g funk'
, u'deep german indie'
, u'deep german punk'
, u'deep gothic post-punk'
, u'deep happy hardcore'
, u'deep hardcore'
, u'deep hardcore punk'
, u'deep hardstyle'
, u'deep house'
, u'deep indian pop'
, u'deep indie pop'
, u'deep indie rock'
, u'deep indie singer-songwriter'
, u'deep italo disco'
, u'deep jazz fusion'
, u'deep jazz guitar'
, u'deep jazz piano'
, u'deep latin alternative'
, u'deep liquid'
, u'deep melodic death metal'
, u'deep melodic hard rock'
, u'deep melodic metalcore'
, u'deep minimal techno'
, u'deep motown'
, u'deep neo-synthpop'
, u'deep neofolk'
, u'deep new wave'
, u'deep nordic folk'
, u'deep northern soul'
, u'deep opera'
, u'deep orchestral'
, u'deep orgcore'
, u'deep pop emo'
, u'deep pop punk'
, u'deep power-pop punk'
, u'deep progressive house'
, u'deep progressive trance'
, u'deep psychobilly'
, u'deep psytrance'
, u'deep punk rock'
, u'deep ragga'
, u'deep rai'
, u'deep regional mexican'
, u'deep smooth jazz'
, u'deep soft rock'
, u'deep soul house'
, u'deep soundtrack'
, u'deep southern soul'
, u'deep space rock'
, u'deep string quartet'
, u'deep sunset lounge'
, u'deep surf music'
, u'deep symphonic black metal'
, u'deep talent show'
, u'deep tech house'
, u'deep thrash metal'
, u'deep trap'
, u'deep turkish pop'
, u'deep uplifting trance'
, u'deep vocal house'
, u'deep vocal jazz'
, u'delta blues'
, u'demoscene'
, u'denver indie'
, u'depressive black metal'
, u'desert blues'
, u'desi'
, u'destroy techno'
, u'detroit hip hop'
, u'detroit techno'
, u'didgeridoo'
, u'digital hardcore'
, u'dirty south rap'
, u'dirty texas rap'
, u'disco'
, u'disco house'
, u'discofox'
, u'dixieland'
, u'djent'
, u'dominican pop'
, u'doo-wop'
, u'doom metal'
, u'doomcore'
, u'doujin'
, u'downtempo'
, u'downtempo fusion'
, u'downtempo trip hop'
, u'drama'
, u'dream pop'
, u'dreamo'
, u'drill and bass'
, u'drone'
, u'drone folk'
, u'drone metal'
, u'drone psych'
, u'drum and bass'
, u'drumfunk'
, u'dub'
, u'dub techno'
, u'dubstep'
, u'dubstep product'
, u'dubsteppe'
, u'duranguense'
, u'dutch hip hop'
, u'dutch house'
, u'dutch pop'
, u'dutch rock'
, u'e6fi'
, u'early music'
, u'early music ensemble'
, u'east coast hip hop'
, u'easy listening'
, u'ebm'
, u'ectofolk'
, u'ecuadoria'
, u'edm'
, u'electric blues'
, u'electro'
, u'electro dub'
, u'electro house'
, u'electro jazz'
, u'electro latino'
, u'electro swing'
, u'electro trash'
, u'electro-industrial'
, u'electroacoustic improvisation'
, u'electroclash'
, u'electrofox'
, u'electronic'
, u'electronica'
, u'electronicore'
, u'electropowerpop'
, u'electropunk'
, u'emo'
, u'emo punk'
, u'enka'
, u'entehno'
, u'environmental'
, u'epicore'
, u'estonian pop'
, u'ethereal gothic'
, u'ethereal wave'
, u'etherpop'
, u'ethiopian pop'
, u'eurobeat'
, u'eurodance'
, u'europop'
, u'euroska'
, u'eurovision'
, u'exotica'
, u'experimental'
, u'experimental dubstep'
, u'experimental psych'
, u'experimental rock'
, u'fado'
, u'fake'
, u'fallen angel'
, u'faroese pop'
, u'fast melodic punk'
, u'fidget house'
, u'filmi'
, u'filter house'
, u'filthstep'
, u'fingerstyle'
, u'finnish hardcore'
, u'finnish hip hop'
, u'finnish indie'
, u'finnish jazz'
, u'finnish metal'
, u'finnish pop'
, u'flamenco'
, u'flick hop'
, u'folk'
, u'folk christmas'
, u'folk metal'
, u'folk punk'
, u'folk rock'
, u'folk-pop'
, u'folk-prog'
, u'folklore argentino'
, u'folkmusik'
, u'footwork'
, u'forro'
, u'fourth world'
, u'freak folk'
, u'freakbeat'
, u'free improvisation'
, u'free jazz'
, u'freestyle'
, u'french folk'
, u'french folk pop'
, u'french hip hop'
, u'french indie pop'
, u'french movie tunes'
, u'french pop'
, u'french punk'
, u'french reggae'
, u'french rock'
, u'full on'
, u'funeral doom'
, u'funk'
, u'funk carioca'
, u'funk metal'
, u'funk rock'
, u'funky breaks'
, u'future ambient'
, u'future garage'
, u'futurepop'
, u'g funk'
, u'gabba'
, u'galego'
, u'gamecore'
, u'gamelan'
, u'gangster rap'
, u'garage pop'
, u'garage punk'
, u'garage punk blues'
, u'garage rock'
, u'gauze pop'
, u'gbvfi'
, u'geek folk'
, u'geek rock'
, u'german ccm'
, u'german hip hop'
, u'german indie'
, u'german metal'
, u'german oi'
, u'german pop'
, u'german pop rock'
, u'german punk'
, u'german show tunes'
, u'german techno'
, u'ghettotech'
, u'ghoststep'
, u'girl group'
, u'glam metal'
, u'glam rock'
, u'glitch'
, u'glitch beats'
, u'glitch hop'
, u'glitter trance'
, u'goa trance'
, u'goregrind'
, u'gospel'
, u'gospel blues'
, u'gospel reggae'
, u'gothic alternative'
, u'gothic americana'
, u'gothic doom'
, u'gothic metal'
, u'gothic post-punk'
, u'gothic rock'
, u'gothic symphonic metal'
, u'grave wave'
, u'greek hip hop'
, u'greek house'
, u'greek indie'
, u'grim death metal'
, u'grime'
, u'grindcore'
, u'grisly death metal'
, u'groove metal'
, u'grunge'
, u'grunge pop'
, u'grupera'
, u'guidance'
, u'gypsy jazz'
, u'hands up'
, u'happy hardcore'
, u'hard alternative'
, u'hard bop'
, u'hard glam'
, u'hard house'
, u'hard rock'
, u'hard stoner rock'
, u'hard trance'
, u'hardcore'
, u'hardcore breaks'
, u'hardcore hip hop'
, u'hardcore punk'
, u'hardcore techno'
, u'hardstyle'
, u'harmonica blues'
, u'harp'
, u'hatecore'
, u'hauntology'
, u'hawaiian'
, u'healing'
, u'heavy alternative'
, u'heavy christmas'
, u'heavy gothic rock'
, u'hi nrg'
, u'highlife'
, u'hindustani classical'
, u'hip hop'
, u'hip hop quebecois'
, u'hip hop tuga'
, u'hip house'
, u'hip pop'
, u'hiplife'
, u'hollywood'
, u'honky tonk'
, u'horror punk'
, u'horrorcore'
, u'house'
, u'hungarian hip hop'
, u'hungarian pop'
, u'hungarian rock'
, u'hurban'
, u'hyphy'
, u'icelandic pop'
, u'idol'
, u'illbient'
, u'indian classical'
, u'indian pop'
, u'indian rock'
, u'indie christmas'
, u'indie dream pop'
, u'indie emo'
, u'indie emo rock'
, u'indie folk'
, u'indie fuzzpop'
, u'indie pop'
, u'indie pop rock'
, u'indie post-punk'
, u'indie psych-pop'
, u'indie r&b'
, u'indie rock'
, u'indie shoegaze'
, u'indie singer-songwriter'
, u'indietronica'
, u'indonesian indie'
, u'indonesian pop'
, u'indorock'
, u'industrial'
, u'industrial metal'
, u'industrial rock'
, u'instrumental post rock'
, u'intelligent dance music'
, u'irish folk'
, u'irish indie'
, u'irish rock'
, u'iskelma'
, u'islamic recitation'
, u'israeli rock'
, u'italian disco'
, u'italian folk'
, u'italian hip hop'
, u'italian indie pop'
, u'italian jazz'
, u'italian pop'
, u'italian pop rock'
, u'italian progressive rock'
, u'italian punk'
, u'italo dance'
, u'j-alt'
, u'j-ambient'
, u'j-core'
, u'j-dance'
, u'j-idol'
, u'j-indie'
, u'j-metal'
, u'j-pop'
, u'j-poppunk'
, u'j-poprock'
, u'j-punk'
, u'j-rap'
, u'j-rock'
, u'j-theme'
, u'jam band'
, u'jangle pop'
, u'jangle rock'
, u'japanese jazztronica'
, u'japanese psychedelic'
, u'japanese r&b'
, u'japanese standards'
, u'japanese traditional'
, u'japanoise'
, u'jazz'
, u'jazz bass'
, u'jazz blues'
, u'jazz brass'
, u'jazz christmas'
, u'jazz funk'
, u'jazz fusion'
, u'jazz metal'
, u'jazz orchestra'
, u'jazz trio'
, u'jerk'
, u'jig and reel'
, u'judaica'
, u'jug band'
, u'juggalo'
, u'jump blues'
, u'jump up'
, u'jumpstyle'
, u'jungle'
, u'k-hop'
, u'k-indie'
, u'k-pop'
, u'k-rock'
, u'kabarett'
, u'karneval'
, u'kc indie'
, u'kindermusik'
, u'kirtan'
, u'kiwi rock'
, u'kizomba'
, u'klapa'
, u'klezmer'
, u'kompa'
, u'kraut rock'
, u'kuduro'
, u'kurdish folk'
, u'kwaito'
, u'la indie'
, u'laboratorio'
, u'laiko'
, u'latin'
, u'latin alternative'
, u'latin christian'
, u'latin christmas'
, u'latin electronica'
, u'latin hip hop'
, u'latin jazz'
, u'latin metal'
, u'latin pop'
, u'latvian pop'
, u'lds'
, u'leeds indie'
, u'levenslied'
, u'liedermacher'
, u'light music'
, u'lilith'
, u'liquid funk'
, u'lithumania'
, u'liturgical'
, u'lo star'
, u'lo-fi'
, u'louisiana blues'
, u'louisville indie'
, u'lounge'
, u'lounge house'
, u'lovers rock'
, u'lowercase'
, u'luk thung'
, u'madchester'
, u'maghreb'
, u'magyar'
, u'makossa'
, u'malagasy folk'
, u'malaysian pop'
, u'mallet'
, u'mambo'
, u'mande pop'
, u'mandopop'
, u'manele'
, u'marching band'
, u'mariachi'
, u'martial industrial'
, u'mashup'
, u'math pop'
, u'math rock'
, u'mathcore'
, u'mbalax'
, u'medieval'
, u'medieval rock'
, u'meditation'
, u'melancholia'
, u'melbourne bounce'
, u'mellow gold'
, u'melodic death metal'
, u'melodic hard rock'
, u'melodic hardcore'
, u'melodic metalcore'
, u'melodic power metal'
, u'melodic progressive metal'
, u'memphis blues'
, u'memphis hip hop'
, u'memphis soul'
, u'merengue'
, u'merengue urbano'
, u'merseybeat'
, u'metal'
, u'metal guitar'
, u'metalcore'
, u'metropopolis'
, u'mexican indie'
, u'mexican rock-and-roll'
, u'mexican son'
, u'mexican traditional'
, u'miami bass'
, u'michigan indie'
, u'microhouse'
, u'military band'
, u'minimal'
, u'minimal dub'
, u'minimal dubstep'
, u'minimal melodic techno'
, u'minimal tech house'
, u'minimal techno'
, u'minimal wave'
, u'mizrahi'
, u'mod revival'
, u'modern blues'
, u'modern classical'
, u'modern country rock'
, u'modern downshift'
, u'modern free jazz'
, u'modern performance'
, u'modern southern rock'
, u'modern uplift'
, u'monastic'
, u'moombahton'
, u'morna'
, u'motivation'
, u'motown'
, u'movie tunes'
, u'mpb'
, u'musica para ninos'
, u'musiikkia lapsille'
, u'musique concrete'
, u'musique pour enfants'
, u'muziek voor kinderen'
, u'nasheed'
, u'nashville sound'
, u'native american'
, u'necrogrind'
, u'neo classical metal'
, u'neo honky tonk'
, u'neo mellow'
, u'neo metal'
, u'neo soul'
, u'neo soul-jazz'
, u'neo-industrial rock'
, u'neo-pagan'
, u'neo-progressive'
, u'neo-psychedelic'
, u'neo-rockabilly'
, u'neo-singer-songwriter'
, u'neo-synthpop'
, u'neo-trad metal'
, u'neo-traditional country'
, u'neoclassical'
, u'neofolk'
, u'nepali'
, u'nerdcore'
, u'neue deutsche harte'
, u'neue deutsche welle'
, u'neurofunk'
, u'neurostep'
, u'new age'
, u'new age piano'
, u'new beat'
, u'new jack smooth'
, u'new jack swing'
, u'new orleans blues'
, u'new orleans jazz'
, u'new rave'
, u'new romantic'
, u'new tribe'
, u'new wave'
, u'new wave pop'
, u'new weird america'
, u'ninja'
, u'nintendocore'
, u'nl folk'
, u'no wave'
, u'noise'
, u'noise pop'
, u'noise punk'
, u'noise rock'
, u'nordic folk'
, u'nordic house'
, u'norteno'
, u'northern irish indie'
, u'northern soul'
, u'norwegian gospel'
, u'norwegian hip hop'
, u'norwegian jazz'
, u'norwegian metal'
, u'norwegian pop'
, u'norwegian punk'
, u'norwegian rock'
, u'nu age'
, u'nu disco'
, u'nu electro'
, u'nu gaze'
, u'nu jazz'
, u'nu metal'
, u'nu skool breaks'
, u'nu-cumbia'
, u'nueva cancion'
, u'nursery'
, u'nwobhm'
, u'nwothm'
, u'nz indie'
, u'oi'
, u'old school hip hop'
, u'old-time'
, u'opera'
, u'operatic pop'
, u'opm'
, u'oratory'
, u'orchestral'
, u'organic ambient'
, u'orgcore'
, u'orquesta tipica'
, u'orquesta tropical'
, u'oshare kei'
, u'ostrock'
, u'outer hip hop'
, u'outlaw country'
, u'outsider'
, u'outsider house'
, u'p funk'
, u'pagan black metal'
, u'pagode'
, u'pakistani pop'
, u'permanent wave'
, u'persian pop'
, u'persian traditional'
, u'perth indie'
, u'peruvian rock']